language: python
python:
  - "3.4"
install:
  - pip install -U setuptools
  - pip install nose coverage mock pytest pytest-coverage
script:
  - python setup.py install
  - pytest
notifications:
  email:
    - forkel@shh.mpg.de
